name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: 安装依赖项（根据平台不同进行处理）
    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++

    - name: Install dependencies on macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake

    # Step 3: 清理构建目录
    - name: Clean build directory
      run: |
        rm -rf build

    # Step 4: 配置项目
    - name: Configure Project with CMake
      run: cmake -S . -B build

    # Step 5: 构建项目
    - name: Build Project
      run: cmake --build build

    # Step 6: 运行测试
    - name: Run Tests
      run: ./build/temperature_control_system
